---
title: "Lab04"
author: "Rodolfo"
date: "28/8/2019"
output: rmarkdown::github_document
---
# Laboratorio 4
```{r, cache=TRUE}
library(tidyr)
library(reshape2)
library(readr)
library(dplyr)
library(stringr)
```

## Intro
```{r, cache=TRUE}
df<- data.frame(row= LETTERS[1:3], a= 1:3, b = 4:6, c = 7:9)
df
```

Melt es de Reshape2
```{r, cache=TRUE}
dfm<- reshape2::melt(df, id="row")
dfm
```

Gather es de Tidyr
```{r, cache=TRUE}
dfg <- gather(df, key="variable", value ="value", a:c)
dfg
```
## Messy Data de Casos
```{r, cache=TRUE}
my_data <- read_csv("Archive/raw.csv") %>% select(-X1)
head(my_data)
```
```{r, cache=TRUE}
melted_data <- gather(my_data, key = "Rango", value = "cases", 3:18)
melted_data %>% head()
```

```{r, cache=TRUE}
tidy_data1 <- melted_data %>% 
  mutate(sex = substr(Rango, 1,1), age= as.factor(substr(Rango,2,5))) %>% 
  select(country, year,sex, age, cases) 
tidy_data1 %>% head()
```

```{r, cache=TRUE}
levels(tidy_data1$age) <- c("0-14", "15-24", "25-34", "35-44", "45-54", "55-64", "65", "u")
tidy_data1 %>% head()
```
## Wide Religion
```{r, cache=TRUE}
load("Archive/wide_religion.Rda")
head(wide_religion)
```

```{r, cache=TRUE}
wide_religion_tidy <- gather(wide_religion, key = "income", value = "freq", 2:11) %>%
  arrange(religion)
head(wide_religion_tidy,10)
```



